// Généré depuis la colonne COULEUR du fichier Excel des couleurs Laurentides.
// Le code provient uniquement de cette colonne.
export const COULEURS_REF: Array<{ name: string; code: string | null }> = [
  { name: "Acadia", code: "P-572" },
  { name: "Acier Oxydé", code: "6241-63" },
  { name: "Allon 3.78l Uraqua Charcoal", code: null },
  { name: "Aluminium Cuivre", code: "P-575" },
  { name: "Ambre", code: "P-516" },
  { name: "Ambre D'automne", code: "P-591" },
  { name: "Ambre D'automne Xl", code: null },
  { name: "Amsterdam", code: "AF-550" },
  { name: "Ancien Brun Commercial Fenêtre", code: "W-126214" },
  { name: "Animation Dlx1159-6", code: null },
  { name: "Anthracite Carbon Métallique", code: "P-375" },
  { name: "Après-midi Ensoleillé", code: "P-356" },
  { name: "Aqua Étoile", code: "6020-83" },
  { name: "Aquarelle", code: "HC-116" },
  { name: "Arc De Constantin", code: "P-6231" },
  { name: "Arche De Passerelle", code: "8005-10F" },
  { name: "Ardoise", code: "P-522" },
  { name: "Argent Brossé", code: "OC-26" },
  { name: "Argile", code: "P-403" },
  { name: "Argile", code: "P-510" },
  { name: "Argile Egyptienne", code: "CSP-1140" },
  { name: "Aromatique 134f", code: null },
  { name: "Ash Gray 5h3", code: null },
  { name: "Asphalte Mouillé", code: null },
  { name: "Aube", code: "CC-50" },
  { name: "Aubergine Premium", code: null },
  { name: "Avocat Audacieux M360-6d Berh", code: null },
  { name: "Azur Des Caraïbes", code: "2058-20" },
  { name: "Baiser De L'amant", code: "P-0067" },
  { name: "Balai De Sauge S370-3", code: null },
  { name: "Balles De Coton", code: "OC-122" },
  { name: "Bananier", code: "6096-74" },
  { name: "Barista", code: "P-597" },
  { name: "Bean Soup", code: "2130-10" },
  { name: "Beige De Bleeker", code: "HC-80" },
  { name: "Beige De Bllker", code: "HC-80" },
  { name: "Beige Lambeth", code: "P-501" },
  { name: "Belle Botte Pr20e16-4", code: null },
  { name: "Bermuda Turquoise", code: "P-728" },
  { name: "Bière D'érable", code: "6119-31" },
  { name: "Black Bean Soup", code: "2130-10" },
  { name: "Black Bean Soup", code: "P-2130" },
  { name: "Black Grey 7021 De Ral", code: null },
  { name: "Black Jack", code: "2133-20" },
  { name: "Blanc", code: "K-1285" },
  { name: "Blanc", code: "P-080" },
  { name: "Blanc Decorateur", code: "CC-20" },
  { name: "Blanc Délicat", code: null },
  { name: "Blanc Naturel", code: "6000-11" },
  { name: "Blanc Nébuleux", code: "CC-40" },
  { name: "Blanc Nébuleux", code: "OC-130" },
  { name: "Blanc Pur", code: "P-430" },
  { name: "Blanc Pur", code: "P-431" },
  { name: "Blanc Shoji", code: null },
  { name: "Blanc Tourterelle", code: "OC-57" },
  { name: "Blanc Était Sur Un Bout De Moulure", code: null },
  { name: "Bleu", code: "P-1903" },
  { name: "Bleu Ardoise", code: "P-5606" },
  { name: "Bleu Bermudes", code: "2061-30" },
  { name: "Bleu Bébé", code: "2056-50" },
  { name: "Bleu Ciel", code: null },
  { name: "Bleu Cobalt", code: "2061-20" },
  { name: "Bleu Crepuscule", code: "3160-22" },
  { name: "Bleu Crépuscule", code: null },
  { name: "Bleu Crépuscule 5c6", code: null },
  { name: "Bleu D'écosse", code: "P-583" },
  { name: "Bleu Danube", code: "2062-30" },
  { name: "Bleu Danube", code: "P-2062" },
  { name: "Bleu De Minuit Xl P31", code: null },
  { name: "Bleu De Polynésie", code: "6003-73" },
  { name: "Bleu Délicat", code: null },
  { name: "Bleu Français", code: "4037-53" },
  { name: "Bleu Fédéral", code: "P-340" },
  { name: "Bleu Féérique", code: "2055-50" },
  { name: "Bleu Glacé", code: "HC-143" },
  { name: "Bleu Héron", code: "P-330" },
  { name: "Bleu Héron Id 8330 De Perspectra Plus Série Weather", code: null },
  { name: "Bleu Héron Wxl 56079 Sur Bout D'aluminium", code: null },
  { name: "Bleu Littoral", code: null },
  { name: "Bleu Littoral - Coastal Blue", code: "P-625" },
  { name: "Bleu Majestic", code: "2051-40" },
  { name: "Bleu Marine", code: "HC-154" },
  { name: "Bleu Minuit", code: null },
  { name: "Bleu Océan", code: "P-542" },
  { name: "Bleu Pervenche", code: "2048-30" },
  { name: "Bleu Rockwell", code: null },
  { name: "Bleu Rockwell 5p2", code: null },
  { name: "Bleu Royal", code: "P-8790" },
  { name: "Bleu Royal 56081 Vicwest", code: null },
  { name: "Bleu Royal De Vicwest 56081", code: null },
  { name: "Bleu Royal De Vicwest 56081 G64-n2187", code: null },
  { name: "Bleu Royal Id 8790", code: null },
  { name: "Bleu Royale", code: "P-5608" },
  { name: "Bleu Étincellant", code: "6152-63" },
  { name: "Blondeur", code: "P-321" },
  { name: "Bloody Mary", code: "6057-65" },
  { name: "Blues", code: "6019-73" },
  { name: "Blé Mûr", code: "P-543" },
  { name: "Bois D'épave", code: "P-557" },
  { name: "Bois D'épave", code: "P-655" },
  { name: "Bois De Chêne Dlx1054-6", code: null },
  { name: "Bois De Fumé 5c7", code: null },
  { name: "Bois De Grange Xl 5x4", code: null },
  { name: "Bois De Santal Xl 5x1", code: null },
  { name: "Bois Fumé", code: null },
  { name: "Bonaparte Rouge", code: "CC-64" },
  { name: "Bora Bora", code: "6522-33" },
  { name: "Bouquet De Mimosa", code: "6510-34" },
  { name: "Bourgogne Spécial", code: null },
  { name: "Bronze 38", code: null },
  { name: "Bronze Fenêtre", code: "P-415" },
  { name: "Bronze À Canon", code: "P-1602" },
  { name: "Brossé", code: "OC-26" },
  { name: "Brume D'acacia", code: null },
  { name: "Brun", code: "6179-83" },
  { name: "Brun", code: "K-7390" },
  { name: "Brun Café", code: "P-326" },
  { name: "Brun Café 56077 De Vicwest", code: null },
  { name: "Brun Café 56077 Vicwest", code: null },
  { name: "Brun Café 8326", code: null },
  { name: "Brun Café De Vicwest Wxl56077", code: null },
  { name: "Brun Chocolat", code: null },
  { name: "Brun Commercial", code: "W-124321" },
  { name: "Brun Fauve", code: "P-569" },
  { name: "Brun Fenêtre", code: null },
  { name: "Brun Foncé", code: "Q-229" },
  { name: "Brun Foncé 56062 De Vicwest", code: null },
  { name: "Brun Foncé De Vicwest Wxl56062", code: null },
  { name: "Brun Foncé Id 8229 Perspectra Plus Series", code: null },
  { name: "Brun Grange", code: null },
  { name: "Brun Metro", code: null },
  { name: "Brun Rockport", code: null },
  { name: "Brun Rockport 5c4", code: null },
  { name: "Brun Universel", code: "P-331" },
  { name: "Buisson De Montagne", code: null },
  { name: "Bulle Brillante", code: "0948-3" },
  { name: "Bâton À Lèvre Rouge", code: null },
  { name: "C Ur À La Canelle", code: "6056-75" },
  { name: "Cachemire", code: "P-514" },
  { name: "Cadmen Claret Ccq05-3", code: null },
  { name: "Café", code: null },
  { name: "Café Suisse", code: "OC-45" },
  { name: "Campagne Crétoise", code: "G-145" },
  { name: "Canari", code: "P-2022" },
  { name: "Cape Anglaise", code: "6232-83" },
  { name: "Caramel Écossais", code: "P-6092" },
  { name: "Caravelle", code: "6171-63" },
  { name: "Carbon Black", code: null },
  { name: "Carbon Métallique", code: null },
  { name: "Caribbean Splash Ppg1150-7 De Ppg Paint", code: null },
  { name: "Caribe Ppu13-01 Dynasty", code: null },
  { name: "Carnaval", code: null },
  { name: "Caroube", code: "P-2137" },
  { name: "Caroube Char Brown", code: "P-2137" },
  { name: "Catalyseur Uraqua", code: "P-3396" },
  { name: "Cedre", code: "P-527" },
  { name: "Cellule Orageuse", code: null },
  { name: "Cerise Noire", code: "6053-85" },
  { name: "Cerise Rouge", code: "6053-75" },
  { name: "Chamois", code: "P-533" },
  { name: "Chamois Antique", code: "P-533" },
  { name: "Champs Doré", code: null },
  { name: "Champs Élysées", code: "6155-52" },
  { name: "Charbon", code: "P-523" },
  { name: "Charcoal K21-279", code: null },
  { name: "Chat Siamois", code: "6203-21" },
  { name: "Cheval Gris", code: "2140-50" },
  { name: "Chinchilla Doux", code: "2135-50" },
  { name: "Châtaigne Bronze", code: null },
  { name: "Ciel Des Andes", code: "P-680" },
  { name: "Cigarillos", code: "6189-63" },
  { name: "Citron Brillant", code: "2020-20" },
  { name: "Citron Le Plus Pâle", code: "0264-0" },
  { name: "Cobalt 5117 De Duchesne", code: null },
  { name: "Cognac Flambé", code: "AF-235" },
  { name: "Confiture De Prunes", code: "P-105" },
  { name: "Coquille D'arachide", code: "4122-42" },
  { name: "Coup De Jeunesse", code: null },
  { name: "Courant Frais", code: "6199-42" },
  { name: "Creme Bavaroise", code: "OC-123" },
  { name: "Creme Gtk Xlp32", code: null },
  { name: "Creme Mat - Cream", code: "P-492" },
  { name: "Crimson Red", code: null },
  { name: "Criquet", code: "CC-542" },
  { name: "Crème", code: "P-482" },
  { name: "Crème", code: "P-492" },
  { name: "Cyprès", code: null },
  { name: "Cèdre", code: "P-527" },
  { name: "Cèdre Pâle Mcx De Bois", code: null },
  { name: "Côte Amalfitaine", code: null },
  { name: "Danse Salsa", code: "6061-73" },
  { name: "Danube Bleu", code: "2062-30" },
  { name: "Dent De Lion Beaut-tone B18-2", code: "0829-4" },
  { name: "Dentelle Delicate", code: "2121-70" },
  { name: "Dentelle Délicate", code: "OC-65" },
  { name: "Dijon Dorée", code: "CC-210" },
  { name: "Dimanche À La Campagne", code: "CC-846" },
  { name: "Douce Sarcelle", code: "OC-13" },
  { name: "Duvet D'oie Blanche", code: "6183-11" },
  { name: "Eau Profonde", code: "6159-73" },
  { name: "Envouté", code: null },
  { name: "Espresso", code: "P-636" },
  { name: "Espresso 5p3", code: null },
  { name: "Espresso Macchiato", code: "6191-73" },
  { name: "Falaise Xl 5x2", code: null },
  { name: "Fenexco", code: "S-42060" },
  { name: "Fer Forgé", code: "2124-10" },
  { name: "Festivité", code: "AF-300" },
  { name: "Feu Profond", code: null },
  { name: "Feuille D'automne", code: "CC-92" },
  { name: "Flamme Tremblotante", code: "1005-3" },
  { name: "Fleur De Coton", code: "6186-31" },
  { name: "Forsythia Jaune Sw6907", code: null },
  { name: "Fou Du Roi Cc34", code: null },
  { name: "Fougère Des Prés", code: null },
  { name: "Fougère Des Prés 5c3", code: null },
  { name: "Fougère Des Prés 5c3 G64-n3517", code: null },
  { name: "Four Point", code: null },
  { name: "Fumée De Bois", code: "4152-42" },
  { name: "Fusain Carbonisé", code: null },
  { name: "Fusain Vicwest", code: null },
  { name: "Fève De Vanille", code: "6188-83" },
  { name: "G64-07486", code: null },
  { name: "Gallon 3.78l Uraqua Bleu Lagune", code: "2063-20" },
  { name: "Genevrier", code: "P-580" },
  { name: "Genévrier", code: "P-580" },
  { name: "Genévrier", code: "P-633" },
  { name: "Glace Noire", code: "6207-83" },
  { name: "Gliffside", code: null },
  { name: "Gomme Rouge", code: null },
  { name: "Gomme Rouge Dlx1187-7", code: null },
  { name: "Goudron Noir", code: "2126-10" },
  { name: "Goût De Résine", code: "6167-31" },
  { name: "Grand Canal Sw 6488 171-c6", code: null },
  { name: "Grand Manan Noir", code: "6161-83" },
  { name: "Grande Prairie", code: "2112-70" },
  { name: "Granite", code: "AF-660" },
  { name: "Granite De Baie-comeau", code: "P-6157" },
  { name: "Graphite 5p5", code: null },
  { name: "Gris", code: "DEV-8301" },
  { name: "Gris Antique", code: "P-561" },
  { name: "Gris Ardent", code: "HC-167" },
  { name: "Gris Basalte", code: null },
  { name: "Gris Brume", code: "P-576" },
  { name: "Gris Cendre", code: null },
  { name: "Gris Colombe", code: "P-534" },
  { name: "Gris D'architecte", code: "6198-73" },
  { name: "Gris Dauphin Dolphin Grey", code: "P-6202" },
  { name: "Gris Distante", code: "OC-68" },
  { name: "Gris Fer", code: null },
  { name: "Gris Fusain", code: null },
  { name: "Gris Fusain 8306 De Ideal Roofing", code: null },
  { name: "Gris Fusain De Vicwest Wxl56072", code: null },
  { name: "Gris Fusain Vicwest Wxl56072", code: null },
  { name: "Gris Hudson 5c2", code: null },
  { name: "Gris Monsieur", code: "P-2062" },
  { name: "Gris Métallique", code: null },
  { name: "Gris Métro", code: "P-0536" },
  { name: "Gris Noir", code: "RAL7021" },
  { name: "Gris Perle 03", code: null },
  { name: "Gris Pierre", code: null },
  { name: "Gris Pierre 5h4", code: null },
  { name: "Gris Revelstocke", code: "6205-73" },
  { name: "Gris Réjent Vicwest 56082", code: null },
  { name: "Gris Sherwin", code: "P-7048" },
  { name: "Griset", code: "2111-50" },
  { name: "Groseille Mxl 10280", code: null },
  { name: "Groseille Mxl10280", code: null },
  { name: "Grotte Sous-marine", code: "6151-83" },
  { name: "Hacienda Talavera Ppg17-03", code: null },
  { name: "Hague Blue 30 De Farrow Ball", code: null },
  { name: "Haricot D'espagne", code: "P-6078" },
  { name: "Harvest", code: "4093-53" },
  { name: "Harvest", code: "5093-53" },
  { name: "Idée Brillante 0807", code: null },
  { name: "Inoubliable", code: "1556-3" },
  { name: "Intrigue P160-6", code: null },
  { name: "Irrésistible Ppg1094-1 De Ppg", code: null },
  { name: "Italian Saffron", code: "PPG-16" },
  { name: "Ivoire", code: "P-302" },
  { name: "Ivoire Antique", code: "P-533" },
  { name: "Jardin Céleste", code: "0457-0" },
  { name: "Jardin Japonais", code: "6168-41" },
  { name: "Jaune", code: "P-301" },
  { name: "Jaune Citrine", code: "2022-20" },
  { name: "Jaune D'oeuf", code: "P-6093" },
  { name: "Jaune India", code: null },
  { name: "Jaune Soleil", code: "2161-40" },
  { name: "Jaune Soleil Duchesne Acier", code: "QC-18685" },
  { name: "Jaune Soleil Qc685 Duchesne", code: null },
  { name: "Jaune Sécurité Rust-oleum", code: null },
  { name: "Jaune Tournesol", code: "6094-54" },
  { name: "Jaune Tournesol Sunflower Yellow", code: "P-6094" },
  { name: "Jaune Van Gogh", code: "P-6094" },
  { name: "Jaune Éclatant", code: "2022-30" },
  { name: "Jean Neuf", code: "6004-63" },
  { name: "Jojoba", code: "AF-460" },
  { name: "Kaki", code: "P-541" },
  { name: "Kc18-4 Doodling Crayonner De Beauty Tone", code: null },
  { name: "Khaki", code: "P-541" },
  { name: "Lagon Profond", code: "P-6003" },
  { name: "Laine D'alpaga", code: "6179-53" },
  { name: "Lait Fouetté À La Vanille", code: "OC-59" },
  { name: "Le Navire Chavire", code: "1457-3" },
  { name: "Lemon Meringue", code: "2023-50" },
  { name: "Limoncello", code: "6511-44" },
  { name: "Linen", code: "P-924" },
  { name: "Littoral", code: null },
  { name: "Littoral Xl 5h3", code: null },
  { name: "Loup", code: "6209-73" },
  { name: "Loup Gris 5x5", code: null },
  { name: "Loup Gris Xl 5x5", code: null },
  { name: "Lumières De Broadway", code: "P-298" },
  { name: "Luzerne", code: "AF-530" },
  { name: "Luzule Des Bois", code: "HC-126" },
  { name: "Luzule Des Bois Avon Green", code: "HC-126" },
  { name: "Majestic Brick 5c5", code: null },
  { name: "Manchester Tan", code: "HC-81" },
  { name: "Mantra", code: "6222-42" },
  { name: "Marilyn", code: "6502-33" },
  { name: "Marlboro Blue", code: "HC-153" },
  { name: "Marvin Bronze G64-n35", code: null },
  { name: "Marée Verte", code: "6145-83" },
  { name: "Mer Adriatique", code: "CSP-660" },
  { name: "Mer Des Caraïbes", code: "6003-53" },
  { name: "Midnigt", code: "2131-20" },
  { name: "Miel De Printemps", code: "6095-32" },
  { name: "Miel De Trèfle", code: "6095-54" },
  { name: "Mist Green", code: "P-256" },
  { name: "Montagnes Selkirk", code: "P-6205" },
  { name: "Moon River Cl24-4", code: null },
  { name: "Mousse Au Chocolat", code: "4101-3" },
  { name: "Murmure Turquoise", code: "4255-1" },
  { name: "Murmure Turquoise", code: "P-4255" },
  { name: "Mère Nature", code: "P-0746" },
  { name: "Nefertiti", code: "6224-21" },
  { name: "Noir", code: "P-525" },
  { name: "Noir Absolu", code: "2133-10" },
  { name: "Noir De Grand Manan", code: null },
  { name: "Noir De Vigne", code: "2128-20" },
  { name: "Noyer", code: "P-593" },
  { name: "Noyer Chocolaté", code: null },
  { name: "Nuages De Nairobi", code: "6197-11" },
  { name: "Nuit D'été", code: "2134-20" },
  { name: "Nuit De New York", code: null },
  { name: "Nuit Des Temps", code: "P-2129" },
  { name: "Nuit Sans Étoiles", code: null },
  { name: "Oie Blanche", code: "OC-17" },
  { name: "Omelette", code: "6093-74" },
  { name: "Orange Sunset Int'l Orange", code: "QC-8234" },
  { name: "Osier", code: null },
  { name: "Outrageux", code: "P-0122" },
  { name: "Pacific Pallisades", code: "P-762" },
  { name: "Palourde De Mer", code: "6193-63" },
  { name: "Panthere Noir", code: "2125-10" },
  { name: "Papier Japonais", code: "6195-21" },
  { name: "Perspectra Plus Série", code: null },
  { name: "Pierre De Cranbrook", code: "P-6205" },
  { name: "Pierre De Rivière", code: "P-555" },
  { name: "Pierre Des Champs", code: "P-204" },
  { name: "Pierre Des Champs 5h6", code: null },
  { name: "Pierre Des Champs Gtk 5h6", code: null },
  { name: "Plaines D'abraham", code: "6129-31" },
  { name: "Plante Grasse", code: "P-566" },
  { name: "Plongeon", code: "6150-42" },
  { name: "Plongée En Eau Profonde Sw 7618", code: null },
  { name: "Pluie Hivernale", code: "6199-53" },
  { name: "Poussière D'étoile", code: "2108-40" },
  { name: "Poussière De Lune", code: "P-513" },
  { name: "Poussière De Turquie", code: "6116-63" },
  { name: "Pure White Sw", code: "P-7005" },
  { name: "Queue De Paon", code: "6160-63" },
  { name: "Raisin Sec", code: "2082-20" },
  { name: "Randall's 5485", code: null },
  { name: "Raton Laveur", code: "2126-20" },
  { name: "Raton Laveur", code: "P-2126" },
  { name: "Reclining Green", code: null },
  { name: "Renard Roux", code: "P-584" },
  { name: "Rivière Nil S420-3", code: null },
  { name: "Rocaille Verte", code: "CC-560" },
  { name: "Rockport Brown 5c4", code: null },
  { name: "Roman Pine", code: "6139-83" },
  { name: "Romarin", code: "HC-157" },
  { name: "Rose Jaune", code: "P-353" },
  { name: "Rouge", code: "S-40211" },
  { name: "Rouge 8250", code: null },
  { name: "Rouge Antique Rouge Dorplex", code: "P-408" },
  { name: "Rouge Brique", code: "P-024" },
  { name: "Rouge Caliente", code: "AF-290" },
  { name: "Rouge Campagne", code: "P-551" },
  { name: "Rouge Colonial", code: "P-248" },
  { name: "Rouge De Cupidon", code: "P-6056" },
  { name: "Rouge Espagnol", code: null },
  { name: "Rouge Foncé", code: "P-250" },
  { name: "Rouge Foncé", code: "P-5606" },
  { name: "Rouge Foncé", code: "QC-16064" },
  { name: "Rouge Foncé", code: "QC-56064" },
  { name: "Rouge Foncé", code: "VW-6064" },
  { name: "Rouge Glaise", code: "2005-10" },
  { name: "Rouge Groseille", code: "P-1323" },
  { name: "Rouge Héritage", code: "HC-181" },
  { name: "Rouge Majestueux", code: null },
  { name: "Rouge Majestueux 5c5", code: null },
  { name: "Rouge Marocain", code: null },
  { name: "Rouge Million Dollars", code: "2003-10" },
  { name: "Rouge Navajo", code: "2171-10" },
  { name: "Rouge Navajo", code: "4076-85" },
  { name: "Rouge Oxyde", code: "RAL3009" },
  { name: "Rouge Pierre", code: "2009-10" },
  { name: "Rouge Positif", code: null },
  { name: "Rouge Rustique", code: "HC-184" },
  { name: "Rouge Tambour Échantillon Sur Bout D'aluminium", code: null },
  { name: "Rouge Tuile", code: null },
  { name: "Rouge Tuile De Vicwest", code: null },
  { name: "Rouge Venitian", code: "P-539" },
  { name: "Rouge Vif", code: "QC-28386" },
  { name: "Rouge Vif Vicwest 56080", code: null },
  { name: "Rouge À Déterminer", code: null },
  { name: "Récolte De Canneberges", code: "M-324" },
  { name: "Régime De Banane", code: "P-6096" },
  { name: "Sable", code: "P-011" },
  { name: "Sable", code: "P-587" },
  { name: "Sable De Désert 5h5", code: null },
  { name: "Sable De Monterey", code: null },
  { name: "Sable De Monterey 5p8", code: null },
  { name: "Sable Du Désert 5h5", code: null },
  { name: "Sable Monterey 5p8", code: null },
  { name: "Sable Saharien", code: "P-6194" },
  { name: "Sarcelle", code: "2055-10" },
  { name: "Sauce Cardinale", code: "P-6057" },
  { name: "Sauge", code: "P-517" },
  { name: "Sel De Mer 217-c1", code: null },
  { name: "Sheffield Ppg1139-5 De Ppg", code: null },
  { name: "Si Étoilé", code: "6020-83" },
  { name: "Sierra", code: "P-577" },
  { name: "Silhouette", code: "AF-655" },
  { name: "Sizzel Dr 76-3 Beautytone", code: null },
  { name: "Skin", code: "6210-11" },
  { name: "Smoked Timber", code: null },
  { name: "Soni Aluminium 50 Gloss", code: null },
  { name: "Soni Pvc", code: null },
  { name: "Sorbet Citronné", code: "P-343" },
  { name: "Sorbet Citronné Sunray", code: "P-343" },
  { name: "Souhait Sous Les Étoiles C15-2", code: "0668-4" },
  { name: "Source De Montagne", code: "6201-52" },
  { name: "Stiffkey Blue", code: "P-281" },
  { name: "Sucre D'érable", code: "F-1491" },
  { name: "Suie", code: "2129-20" },
  { name: "Sultan Doré Sultan Gold 128g", code: null },
  { name: "Sunny Afternoon", code: null },
  { name: "Sunshine", code: "2021-30" },
  { name: "Sur Le Plat", code: null },
  { name: "Tan", code: "P-507" },
  { name: "Tart Orange", code: "P-510" },
  { name: "Tarte Au Citron", code: null },
  { name: "Taupe Parfait", code: null },
  { name: "Teint Rosé", code: "2091-50" },
  { name: "Teinture Brun Spécial", code: "P-232" },
  { name: "Terra Cotta Rose 10yr 16", code: "P-407" },
  { name: "Terre Cuite Terra Red Ideal Roofing- 10 Lustre", code: null },
  { name: "Terre De Soleil", code: "2161-40" },
  { name: "Thym Citron", code: "6141-53" },
  { name: "Tire À La Fraise", code: null },
  { name: "Tomate Séchée", code: "6057-85" },
  { name: "Tomate Séchées", code: "CC-62" },
  { name: "Tortue", code: "P-475" },
  { name: "Trempette D'artichaut", code: "6196-31" },
  { name: "Truffe Aux Framboises", code: "2080-10" },
  { name: "Truite Saumonée", code: null },
  { name: "Trèfle Violet Sw6564 102-ca", code: null },
  { name: "Trèfle À Quatre Feuille C34-3", code: "1563-4" },
  { name: "Trèfle À Quatre Feuilles Four Leaf Clover C34-3", code: "1653-4" },
  { name: "Très Marine Very Navy M500-7d", code: null },
  { name: "Uragua Si", code: "P-593" },
  { name: "Uraqua Black Grey 7021 De Ral", code: null },
  { name: "Uraqua Espresso", code: null },
  { name: "Uraqua Fougère Des Prés 5c3 G64-n3517", code: null },
  { name: "Uraqua Noyer", code: "P-593" },
  { name: "Uraqua Outrageux", code: "P-0122" },
  { name: "Uraqua Rouge Campagne", code: "P-551" },
  { name: "Vague Bleue", code: "6003-63" },
  { name: "Vague De Minuit", code: "P-509" },
  { name: "Vague De Minuit Midnight Surf", code: null },
  { name: "Valériane", code: "CC-66" },
  { name: "Veille De Tempête", code: "CC-844" },
  { name: "Vert Antique", code: "2136-40" },
  { name: "Vert Antique", code: "P-558" },
  { name: "Vert Asaret", code: null },
  { name: "Vert Balsamine", code: null },
  { name: "Vert Bonneville", code: "P-598" },
  { name: "Vert Bonneville Green", code: "P-598" },
  { name: "Vert Foncé Vicwest 56073", code: null },
  { name: "Vert Foret", code: "P-556" },
  { name: "Vert Forêt", code: "QC-56078" },
  { name: "Vert Gazon", code: "RAL6010" },
  { name: "Vert Gedney", code: null },
  { name: "Vert Marin", code: null },
  { name: "Vert Mélèze Wxl56085 Vw", code: null },
  { name: "Vert Olive", code: "HC-112" },
  { name: "Vert Ombré", code: "CC-550" },
  { name: "Vert Ombré", code: "P-1495" },
  { name: "Vert Rustique", code: "HC-121" },
  { name: "Vert Sauge", code: "P-517" },
  { name: "Vert Spécial G64-n3625", code: null },
  { name: "Vert St-louis", code: "HC-113" },
  { name: "Vert Suffield", code: null },
  { name: "Vert Sur Bloc De Bois", code: null },
  { name: "Vert Sur Échantillon De Bois De 4 1", code: null },
  { name: "Vert Tilleul", code: null },
  { name: "Vert Toscane", code: "2140-20" },
  { name: "Vieux Jeans", code: "6004-31" },
  { name: "Vintage Linen", code: null },
  { name: "Voile Cendré", code: null },
  { name: "Walnut", code: "P-593" },
  { name: "Willow", code: "CC-542" },
  { name: "Yellowstone", code: "P-573" },
  { name: "Éclipse Solaire", code: "2128-10" },
  { name: "Étain", code: "HC-172" },
  { name: "Étain 5h2", code: null },
  { name: "Île Au Sable", code: "CC-320" },
];
