import { extractCadreAluRows } from "../src/lib/cadresAlu.server";
import { COULEURS_REF } from "../src/lib/couleursRef";
import { readFileSync } from "fs";
const buf = readFileSync("/mnt/user-uploads/03.MDB");
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset+buf.byteLength) as ArrayBuffer;
const couleurs = [...COULEURS_REF.map(c=>({name:c.name, code:c.code ?? null})), {name:"Noir",code:"P-525"},{name:"Brun Commercial",code:"P-562"}];
const rows = extractCadreAluRows(ab, null, undefined, couleurs as any);
const counts = new Map<string,number>();
for(const r of rows) counts.set(r.couleur, (counts.get(r.couleur)??0)+1);
console.log([...counts.entries()].sort((a,b)=>b[1]-a[1]).slice(0,60).map(([k,v])=>`${v}\t${k}`).join("\n"));
