/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortesAdminRouteImport } from './routes/portes-admin'
import { Route as PortesRouteImport } from './routes/portes'
import { Route as FenetresRouteImport } from './routes/fenetres'
import { Route as DelaysAdminRouteImport } from './routes/delays-admin'
import { Route as DelaysRouteImport } from './routes/delays'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const PortesAdminRoute = PortesAdminRouteImport.update({
  id: '/portes-admin',
  path: '/portes-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortesRoute = PortesRouteImport.update({
  id: '/portes',
  path: '/portes',
  getParentRoute: () => rootRouteImport,
} as any)
const FenetresRoute = FenetresRouteImport.update({
  id: '/fenetres',
  path: '/fenetres',
  getParentRoute: () => rootRouteImport,
} as any)
const DelaysAdminRoute = DelaysAdminRouteImport.update({
  id: '/delays-admin',
  path: '/delays-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DelaysRoute = DelaysRouteImport.update({
  id: '/delays',
  path: '/delays',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/delays': typeof DelaysRoute
  '/delays-admin': typeof DelaysAdminRoute
  '/fenetres': typeof FenetresRoute
  '/portes': typeof PortesRoute
  '/portes-admin': typeof PortesAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/delays': typeof DelaysRoute
  '/delays-admin': typeof DelaysAdminRoute
  '/fenetres': typeof FenetresRoute
  '/portes': typeof PortesRoute
  '/portes-admin': typeof PortesAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/delays': typeof DelaysRoute
  '/delays-admin': typeof DelaysAdminRoute
  '/fenetres': typeof FenetresRoute
  '/portes': typeof PortesRoute
  '/portes-admin': typeof PortesAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/delays'
    | '/delays-admin'
    | '/fenetres'
    | '/portes'
    | '/portes-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/delays'
    | '/delays-admin'
    | '/fenetres'
    | '/portes'
    | '/portes-admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/delays'
    | '/delays-admin'
    | '/fenetres'
    | '/portes'
    | '/portes-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DelaysRoute: typeof DelaysRoute
  DelaysAdminRoute: typeof DelaysAdminRoute
  FenetresRoute: typeof FenetresRoute
  PortesRoute: typeof PortesRoute
  PortesAdminRoute: typeof PortesAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portes-admin': {
      id: '/portes-admin'
      path: '/portes-admin'
      fullPath: '/portes-admin'
      preLoaderRoute: typeof PortesAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portes': {
      id: '/portes'
      path: '/portes'
      fullPath: '/portes'
      preLoaderRoute: typeof PortesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fenetres': {
      id: '/fenetres'
      path: '/fenetres'
      fullPath: '/fenetres'
      preLoaderRoute: typeof FenetresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delays-admin': {
      id: '/delays-admin'
      path: '/delays-admin'
      fullPath: '/delays-admin'
      preLoaderRoute: typeof DelaysAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delays': {
      id: '/delays'
      path: '/delays'
      fullPath: '/delays'
      preLoaderRoute: typeof DelaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DelaysRoute: DelaysRoute,
  DelaysAdminRoute: DelaysAdminRoute,
  FenetresRoute: FenetresRoute,
  PortesRoute: PortesRoute,
  PortesAdminRoute: PortesAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
